### PR TITLE
add new metascope for Svelte Components

### PR DESCRIPTION
**Pull request by basaran**
Add meta.tag.component.form.html to elements that start with capital letters, and also <tag:property> style tags.

image

image

### CODE REVIEW

**Comment by corneliusio** [comment]
@basaran Thanks! Will take a look ASAP and merge if everything looks good (which I'm assuming it will).

**Comment by basaran** [comment]
great, let me know if I can help with anything.

**Comment by basaran** [comment]
hello, what are the conflicts? I can send another PR.

**Comment by corneliusio** [comment]
@basaran Hey, sorry for letting this hang out for so long. I needed to have these changes made in `Svelte.sublime-syntax.yaml-macros` and then built with the YAML Macros plugin. I made a few adjustments, biggest being using `meta.tag.component.any.html` for the meta scope instead of `meta.tag.component.form.html`. But you should see the new meta scope on all the Svelte component tags now. Package should update automatically soon.

https://github.com/corneliusio/svelte-sublime/commit/16808be787bb2d879c819ee445cc1cbd8ce57a55

**Pull request closed without merging**
